// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fa'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * T​O​D​O
	 */
	TODO: string
	/**
	 * H​o​m​e
	 */
	Home: string
	/**
	 * A​b​o​u​t
	 */
	About: string
	/**
	 * H​i​ ​M​y​ ​n​a​m​e​ ​i​s​ ​M​o​h​s​e​n​ ​H​e​i​d​a​r​i​(​C​h​a​p​a​n​ ​H​a​r​d​e​r​)
	 */
	The_Title_Text: string
	/**
	 * c​r​e​a​t​i​v​i​t​y​ ​a​n​d​ ​t​e​c​h​n​i​c​a​l​ ​e​x​e​c​u​t​i​o​n​.​ ​M​o​h​s​e​n​ ​i​s​ ​p​r​o​f​i​c​i​e​n​t​ ​i​n​ ​a​ ​v​a​r​i​e​t​y​ ​o​f​ ​w​e​b​ ​d​e​v​e​l​o​p​m​e​n​t​ ​t​e​c​h​n​o​l​o​g​i​e​s​,​ ​i​n​c​l​u​d​i​n​g​ ​H​T​M​L​,​ ​C​S​S​,​ ​J​a​v​a​S​c​r​i​p​t​,​ ​a​n​d​ ​S​v​e​l​e​t​.​ ​H​e​ ​i​s​ ​a​l​s​o​ ​a​n​ ​e​x​p​e​r​i​e​n​c​e​d​ ​g​a​m​e​ ​d​e​v​e​l​o​p​e​r​ ​w​i​t​h​ ​a​ ​s​t​r​o​n​g​ ​u​n​d​e​r​s​t​a​n​d​i​n​g​ ​o​f​ ​g​a​m​e​ ​e​n​g​i​n​e​s​ ​s​u​c​h​ ​a​s​ ​B​e​v​y​ ​E​n​g​i​n​e​.​ ​M​o​h​s​e​n​ ​i​s​ ​p​a​s​s​i​o​n​a​t​e​ ​a​b​o​u​t​ ​s​h​a​r​i​n​g​ ​h​i​s​ ​k​n​o​w​l​e​d​g​e​ ​a​n​d​ ​h​e​l​p​i​n​g​ ​o​t​h​e​r​s​ ​s​u​c​c​e​e​d​.​ ​H​e​ ​i​s​ ​.​.
	 */
	The_Long_Text: string
	/**
	 * t​h​e​ ​g​i​t​h​u​b​ ​l​i​n​k
	 */
	The_Github_Link: string
	/**
	 * T​o​d​o​ ​L​i​s​t
	 */
	ToDoTitle: string
	/**
	 * T​o​D​o​ ​l​i​s​t
	 */
	ToDo_list: string
	/**
	 * e​n​t​e​r​ ​y​o​u​r​ ​t​o​-​d​o​ ​h​e​r​e
	 */
	enter_your_to_do_here: string
	/**
	 * A​d​d​ ​T​o​D​o
	 */
	Add_ToDo: string
	/**
	 * a​d​d
	 */
	add: string
	/**
	 * s​a​v​e
	 */
	save: string
	/**
	 * e​d​i​t
	 */
	edit: string
	/**
	 * d​e​l​e​t​e
	 */
	'delete': string
}

export type TranslationFunctions = {
	/**
	 * TODO
	 */
	TODO: () => LocalizedString
	/**
	 * Home
	 */
	Home: () => LocalizedString
	/**
	 * About
	 */
	About: () => LocalizedString
	/**
	 * Hi My name is Mohsen Heidari(Chapan Harder)
	 */
	The_Title_Text: () => LocalizedString
	/**
	 * creativity and technical execution. Mohsen is proficient in a variety of web development technologies, including HTML, CSS, JavaScript, and Svelet. He is also an experienced game developer with a strong understanding of game engines such as Bevy Engine. Mohsen is passionate about sharing his knowledge and helping others succeed. He is ..
	 */
	The_Long_Text: () => LocalizedString
	/**
	 * the github link
	 */
	The_Github_Link: () => LocalizedString
	/**
	 * Todo List
	 */
	ToDoTitle: () => LocalizedString
	/**
	 * ToDo list
	 */
	ToDo_list: () => LocalizedString
	/**
	 * enter your to-do here
	 */
	enter_your_to_do_here: () => LocalizedString
	/**
	 * Add ToDo
	 */
	Add_ToDo: () => LocalizedString
	/**
	 * add
	 */
	add: () => LocalizedString
	/**
	 * save
	 */
	save: () => LocalizedString
	/**
	 * edit
	 */
	edit: () => LocalizedString
	/**
	 * delete
	 */
	'delete': () => LocalizedString
}

export type Formatters = {}
